[package]
name = "coder-ideas"
version = "0.1.0"
authors = ["之外 <excepts@featx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
mysql_async = "0.23.0"