POST http://{{SERVER_HOST}}:{{CODER_PORT}}/project/domain
Content-Type: application/json

{
  "code": "",
  "project_code": "PJT18ixdv4mhftc",
  "name": "Comment",
  "properties": [{
    "name": "code",
    "type": 0
  },{
    "name": "target",
    "type": 0
  },{
    "name": "targetCode",
    "type": 0
  },{
    "name": "userCode",
    "type": 0
  },{
    "name": "content",
    "type": 0
  },{
    "name": "type",
    "type": 1
  }]
}