POST http://{{SERVER_HOST}}:{{CODER_PORT}}/project
Content-Type: application/json

{
  "code": "",
  "name": "Musca",
  "type": 1,
  "template_code": "TPL18iksayna0k0",
  "image_url": "",
  "language_code": "LAN100001",
  "framework_code": "FRW100001",
  "repo_url": "https://github.com/sta2ry/Musca.git",
  "branch": "coder",
  "api_token": "",
  "variables": "{\"packageRoot\": \"org.featx.sta2ry.musca\"}"
}
###:
GET http://{{SERVER_HOST}}:{{CODER_PORT}}/project?code=PJTpbupb9gpm4w
###:
GET http://{{SERVER_HOST}}:{{CODER_PORT}}/project/detail?code=PJTpbupb9gpm4w
###
POST http://{{SERVER_HOST}}:{{CODER_PORT}}/project/commit
Content-Type: application/json

{
    "project_code": "PJT18mh43d2r0b4",
    "author": "Excepts",
    "email": "ex7ept@featx.org"
}