POST http://{{SERVER_HOST}}:{{CODER_PORT}}/template
Content-Type: application/json

{
    "language_code": "LAN100001",
    "framework_code": "FRW100001",
    "name": "Spring-Cloud-Alibaba",
    "repo_url": "https://github.com/featx/spring-cloud-alibaba",
    "branch": "master",
    "api_token": "36a9d35592720bd698927bbd0820ce8df3743287",
    "default_rule": "{\"module-\": \"${project.name|lower}-\",\"org/featx/templet/app\": \"${project.packageRoot|path}\", \"org.featx.templet.app\": \"${project.packageRoot|dot}\"}",
    "comment": ""
}

###:
PUT http://{{SERVER_HOST}}:{{CODER_PORT}}/template
Content-Type: application/json

{
    "code": "TPL18iksayna0k0"
}

###:
PUT http://{{SERVER_HOST}}:{{CODER_PORT}}/template/repo
Content-Type: application/json

{
  "code": "TPL18iksayna0k0"
}