POST http://{{SERVER_HOST}}:{{CODER_PORT}}/template/rule
Content-Type: application/json

{
	"code": "",
	"type": 1,
    "engine": 0,
    "name": "Data-MySQL-Test",
    "template_code": "TPL18iksayna0k0",
    "path": "module-data/src/test/resources/db/migration",
    "data": {
        "org/featx/templet/app": "${project.packageRoot|path}",
        "org.featx.templet.app": "${project.packageRoot|dot}",
        "DomainFeatureModule" : "${domain.name|camel}",
        "domainFeatureModule" : "${domain.name|lowerCamel}",
        "domain_feature_module": "${domain.name|snake}",
        "domain-feature-module": "${domain.name|dash}"
        },
    "comment": "Data MySQL Test"
}

###:
