data_source:
  mysql:
    host: 172.17.0.2
    port: 3306
    database: coder
    username: coder
    password: coder
version_control:
  git:
    templates: /usr/local/coder/templates
    workspace: /usr/local/coder/workspace
